### ISSUE TITLE
gunicorn config hardcoded

### ISSUE THREAD

**Issue by r-lindner** [TeraIT-at/netbox-formula#1]
Hello,
I'm using your netbox formula and after some head scratching because of strange defaults (will send another issue later) it worked wonderfully. Now I want to change logging settings for gunicorn but **netbox.service** and **gunicorn.py** are locked down by your formula and you don't allow custom config options in it. For the service file I could use /etc/systemd/system/netbox.service.d/file.conf and overwrite the ExecStart line but in my opinion a for loop to write some custom options from the pillar to gunicorn.py would be nice.

https://github.com/TeraIT-at/netbox-formula/blob/0ae187b2b425d650e9e32b11ccaa0ed412449f44/netbox/files/gunicorn_config_systemd.py#L9

Thanks for your hard work :)

**Comment by joni1993** [comment]
Hi,
thank you for your request and your appreciation
Does #3 fit your needs?

**Comment by r-lindner** [comment]
this looks good - apart from a missing pipe in pillar.example line 146 ;-)

**Comment by joni1993** [comment]
dang - fought quite too much with yaml and jinja for today ;)
